### ISSUE TITLE
getSelectedItems()  issue.

### ISSUE THREAD

**Issue by jaypoojara** [miteshpithadiya/MultiSelectWidget#2]
When i use getSelectedItems() it gives me empty arraylist.
but if i click on clear and than press on ok button it gives me full selected item list.

**Comment by miteshpithadiya** [comment]
Hi, thanks for raising the issue. I have resolved the issue and have released a new version 0.0.2 with the fix.

**Comment by jaypoojara** [comment]
anytime.
actually i solved it yesterday but forgot to post here.
anyway thanks for awesome library.
